---
title: "Cover_elevation_stats_fig"
author: "Melissa DeSiervo"
date: "4/7/2021"
output: html_document
---

library(vegan)
library(indicspecies)
library(tidyverse)
library(data.table)
library(ggplot2)
library(gplots)
library(rcompanion)
library(betapart)
library(weights)
library(stringr)
library(viridis)



```{r setup, include=FALSE}

###import file##


##read in table with species data
sp_imp<-read.csv("C:/Users/Melissa/Dropbox/Sugar Creek Aug 2020/russian_species.csv", header=TRUE)


###reed in long tree data###
tree_long<-read.csv("C:/Users/Melissa/Dropbox/Sugar Creek Aug 2020/tree_long.csv", header=TRUE)

###create new columns with PLOT YEAR and SPECIES LAYER###

tree_long2<-tree_long %>% mutate(PLOTYEAR= paste0(Plot, Year))%>% mutate(SPECIES2= paste0(SpeciesCode, layer2))

###create new column with OTV transformation###

tree_long3<-tree_long2 %>% mutate(OTV = 1.415*log(Cover) + 2)

hist(tree_long3$Class)
hist(tree_long3$Cover)
hist(tree_long3$OTV)

####Site X Species matrix with Cover###

tree_long4<-tree_long3 %>% select(PLOTYEAR, SPECIES2, Cover)

tree.wideCover <- reshape(tree_long4, idvar = "PLOTYEAR", timevar = "SPECIES2", direction = "wide")

names(tree.wideCover) <- gsub("Cover.", "", names(tree.wideCover))

# Fill in NA's with zeros in wide data set
tree.wideCover[is.na(tree.wideCover)] <- 0


####Site X Species matrix with OTV###

tree_long5<-tree_long3 %>% select(PLOTYEAR, SPECIES2, OTV)

tree.wideOTV <- reshape(tree_long5, idvar = "PLOTYEAR", timevar = "SPECIES2", direction = "wide")

names(tree.wideOTV) <- gsub("Cover.", "", names(tree.wideCover))

tree.wideOTV[is.na(tree.wideOTV)] <- 0

####Number of plotyears (292), matches the old file we had###


##read in table with env data
env_imp<-read.csv("C:/Users/Melissa/Dropbox/Sugar Creek Aug 2020/sawyer_topo_data_09212020.csv", header=TRUE)
#make year a factor
env_imp$Year<-as.factor(env_imp$Year)


###merge env and sp data cover
all_datCover<-merge(tree.wideCover, env_imp, by="PLOTYEAR")

all_datOTV<-merge(tree.wideOTV, env_imp, by="PLOTYEAR")


##read in ABCO results from ERIK###
#ABCOcan<-read.csv("C:/Users/Mitzi/Desktop/Academic Collaborations/Sugar Creek Aug 2020/ABCO_CAN.csv", header=TRUE)


##read in wide plot-level BCM (downscaled climate data) ##
#plotbcm_wide<-read.csv("C:/Users/Melissa/Dropbox/Sugar Creek Aug 2020/Plot_BCM_WaterYear_Monthly_wide.csv", header=TRUE)

#covert to long##
#plotbcm_long <- gather(plotbcm_wide, ID, measurement, A01:C05, factor_key=TRUE)

##then make weather variables wide###

#plotbcm2 <- spread(plotbcm_long, Var, measurement)

######merge the plot bcm with the env attributes of plots#####

#env_imp2<-env_imp %>% select(ID, Easting, Northing, ELEV, HLI, TPI_25)

#bcm_plot<-merge(plotbcm2, env_imp2, by="ID")

##filter to the years of interest###


#bcm_plot$Year

#bcm_plot19592014<-subset(bcm_plot, Year > 1957)

##remove duplicates##

#bcm_plot19592014_2<-unique(bcm_plot19592014)

#bcm_plot19592014_2$Month <- factor(bcm_plot19592014_2$Month, levels = c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"))

##add column water year## (so that Oct - Sept = one precipitation season)

#bcm_plot19592014_3<-bcm_plot19592014_2 %>% mutate(wyear = ifelse(Month=="Oct"|Month=="Nov"|Month=="Dec", Year, Year-1))%>%select(ID, Year, wyear, Month, ELEV, HLI, Easting, Northing, aet, cwd, pck, pet, ppt, tmn, tmx)




```

```{r sum up layers for total cover COVER, echo=FALSE}

########sum strata by species
##abco
tree.wideCover$ABCO<-tree.wideCover$ABCOCAN +tree.wideCover$ABCOSAP+tree.wideCover$ABCOSEED
##ablas
tree.wideCover$ABLAS<-tree.wideCover$ABLASCAN +tree.wideCover$ABLASSAP+tree.wideCover$ABLASSEED
##abma
tree.wideCover$ABMA<-tree.wideCover$ABMACAN+tree.wideCover$ABMASAP+tree.wideCover$ABMASEED
##cade
tree.wideCover$CADE<-tree.wideCover$CADECAN+tree.wideCover$CADESAP+tree.wideCover$CADESEED
##picbre
tree.wideCover$PIBR<-tree.wideCover$PICBRECAN+tree.wideCover$PICBRESAP+tree.wideCover$PICBRESEED
##piceng
tree.wideCover$PIEN<-tree.wideCover$PICENGCAN+tree.wideCover$PICENGSAP+tree.wideCover$PICENGSEED
##pincon
tree.wideCover$PICO<-tree.wideCover$PINCONCAN+tree.wideCover$PINCONSAP+tree.wideCover$PINCONSEED
##pinlam
tree.wideCover$PILA<-tree.wideCover$PINLAMCAN+tree.wideCover$PINLAMSAP+tree.wideCover$PINLAMSEED
##pinmon
tree.wideCover$PIMO<-tree.wideCover$PINMONCAN+tree.wideCover$PINMONSAP+tree.wideCover$PINMONSEED
##pinpon
tree.wideCover$PIPO<-tree.wideCover$PINPONCAN+tree.wideCover$PINPONSAP+tree.wideCover$PINPONSEED
##psme
tree.wideCover$PSME<-tree.wideCover$PSMECAN+tree.wideCover$PSMESAP+tree.wideCover$PSMESEED
##tsme
tree.wideCover$TSME<-tree.wideCover$TSMERCAN+tree.wideCover$TSMERSAP+tree.wideCover$TSMERSEED

####

totalcover<-tree.wideCover %>% select(PLOTYEAR, ABCO:TSME)

totalcover_2<-separate(data = totalcover, col = PLOTYEAR, into = c("PLOT", "YEAR"), sep=3)

totalcover_long <- gather(totalcover_2, SPECIES, TotalCover, ABCO:TSME, factor_key=TRUE)


avgcovertotal<-totalcover_long %>% group_by(YEAR, SPECIES) %>% dplyr::summarise(meancover=mean(TotalCover, na.rm=TRUE),sdcover=sd(TotalCover, na.rm=TRUE),secover=sd(TotalCover, na.rm=TRUE)/sqrt(n()))



```


```{r sum up layers for total cover OTV, echo=FALSE}

########sum strata by species
##abco
tree.wideOTV$ABCO<-tree.wideOTV$ABCOCAN +tree.wideOTV$ABCOSAP+tree.wideOTV$ABCOSEED
##ablas
tree.wideOTV$ABLAS<-tree.wideOTV$ABLASCAN +tree.wideOTV$ABLASSAP+tree.wideOTV$ABLASSEED
##abma
tree.wideOTV$ABMA<-tree.wideOTV$ABMACAN+tree.wideOTV$ABMASAP+tree.wideOTV$ABMASEED
##cade
tree.wideOTV$CADE<-tree.wideOTV$CADECAN+tree.wideOTV$CADESAP+tree.wideOTV$CADESEED
##picbre
tree.wideOTV$PIBR<-tree.wideOTV$PICBRECAN+tree.wideOTV$PICBRESAP+tree.wideOTV$PICBRESEED
##piceng
tree.wideOTV$PIEN<-tree.wideOTV$PICENGCAN+tree.wideOTV$PICENGSAP+tree.wideOTV$PICENGSEED
##pincon
tree.wideOTV$PICO<-tree.wideOTV$PINCONCAN+tree.wideOTV$PINCONSAP+tree.wideOTV$PINCONSEED
##pinlam
tree.wideOTV$PILA<-tree.wideOTV$PINLAMCAN+tree.wideOTV$PINLAMSAP+tree.wideOTV$PINLAMSEED
##pinmon
tree.wideOTV$PIMO<-tree.wideOTV$PINMONCAN+tree.wideOTV$PINMONSAP+tree.wideOTV$PINMONSEED
##pinpon
tree.wideOTV$PIPO<-tree.wideOTV$PINPONCAN+tree.wideOTV$PINPONSAP+tree.wideOTV$PINPONSEED
##psme
tree.wideOTV$PSME<-tree.wideOTV$PSMECAN+tree.wideOTV$PSMESAP+tree.wideOTV$PSMESEED
##tsme
tree.wideOTV$TSME<-tree.wideOTV$TSMERCAN+tree.wideOTV$TSMERSAP+tree.wideOTV$TSMERSEED


totalOTV<-tree.wideOTV %>% select(PLOTYEAR, ABCO:TSME)

totalOTV_2<-separate(data = totalOTV, col = PLOTYEAR, into = c("PLOT", "YEAR"), sep=3)

totalOTV_long <- gather(totalOTV_2, SPECIES, TotalOTV, ABCO:TSME, factor_key=TRUE)

totalOTV_long2<-as.data.frame(lapply(totalOTV_long, function(x) ifelse(is.infinite(x), 0, x)))



avgOTVtotal<-totalOTV_long%>% group_by(YEAR, SPECIES) %>% dplyr::summarise(meanOTV=mean(TotalOTV, na.rm=TRUE),sdOTV=sd(TotalOTV, na.rm=TRUE),seOTV=sd(TotalOTV, na.rm=TRUE)/sqrt(n()))


```


```{r not yet working... weighted t tests elevation by layer}

#####COVER########

tree_longplot<-merge(tree_long3, env_imp[3:6], by="PLOTYEAR")

tree_longplot$ELEV<-as.numeric(tree_longplot$ELEV)

###subset dataframe by species/ layer##

elev1969Cover<-tree_longplot%>%filter(Year=="1969")%>%filter(Cover>0)
elev2015Cover<-tree_longplot%>%filter(Year=="2015")%>%filter(Cover>0)

## split the dataframe by species / layer##

dist_dat_split1969Cover<-split.data.frame(x = elev1969Cover,f = elev1969Cover$SPECIES2)
dist_dat_split2015Cover<-split.data.frame(x = elev2015Cover,f = elev2015Cover$SPECIES2)

## weighted t test for elevation#####

###notworking...###

weightedttests<-as.data.frame(stack(mapply(function(x, y) wtd.t.test(x$ELEV,y$ELEV, weight=x$Cover, weighty=y$Cover, total_dist_dat_split1969Cover, total_dist_dat_split2015Cover))))





##this isnt working...need to troubleshoot the apply function##


### weighted elevation averages###
weightedmean1969<-stack(lapply(X = dist_dat_split1969Cover,function(t){
  means1969<-weighted.mean(t$ELEV, t$Cover)
  return(means1969)
}
))
 
weightedmean2015<-stack(lapply(X = dist_dat_split2015Cover,function(t){
  means2015<-weighted.mean(t$ELEV, t$Cover)
  return(means2015)
}
))

elev1969model <- lm(values ~ 1, data = weightedmean1969)
elev2015model <- lm(values ~ 1, data = weightedmean2015)

par(mfrow = c(2, 2))
plot(elev1969model)

#####OTVR########


```



```{r Wilcoxon tests canopy cover by layer COVER}


##wilcox signed rank tests by layer##

try<-gather(all_datCover, SPECIES,Cover, ABCOCAN:TSMERSEED) ##keep the zeroes##
try$SPECIES<-as.factor(try$SPECIES)

###subset dataframe by species/ layer##

elev1969withzeros<-try%>%filter(Year=="1969")
elev2015withzeros<-try%>%filter(Year=="2015")

dist_dat_split1969_withzeros<-split.data.frame(x = elev1969withzeros,f = elev1969withzeros$SPECIES)
dist_dat_split2015_withzeros<-split.data.frame(x = elev2015withzeros,f = elev2015withzeros$SPECIES)


## wilcoxon signed rank tests for layer #####
wilcoxbylayerteststat<-as.data.frame(stack(mapply(function(x, y) wilcox.test(x$Cover,y$Cover, paired=TRUE)$statistic, dist_dat_split1969_withzeros, dist_dat_split2015_withzeros)))

wilcoxbylayertestpval<-as.data.frame(stack(mapply(function(x, y) wilcox.test(x$Cover,y$Cover, paired=TRUE)$p.value, dist_dat_split1969_withzeros, dist_dat_split2015_withzeros)))

tests<-mapply(function(x, y) wilcox.test(x$Cover,y$Cover, paired=TRUE), dist_dat_split1969_withzeros, dist_dat_split2015_withzeros)

wilcoxbylayertestpval$values<-round(wilcoxbylayertestpval$values,6)

#####we've run four tests (seedlings, saplings, canopy, and sum total), so let's use the adjustment of 0.05/4 = 0.0125 for significance (two asterisks) and 0.1/4 = 0.025 for marginal significance (one asterisk). 

wilcoxbylayertestpval <- data.table(wilcoxbylayertestpval)
wilcoxbylayertestpval$signif <- ifelse(wilcoxbylayertestpval$values < 0.0125,"significant","not significant")

```




```{r Wilcoxon tests canopy cover by layer OTV}


##wilcox signed rank tests by layer##

tryOTV<-gather(all_datOTV, SPECIES,OTV, ABCOCAN:TSMERSEED) ##keep the zeroes##

tryOTV$SPECIES<-as.factor(tryOTV$SPECIES)

tryOTV$OTV<-as.numeric(tryOTV$OTV)

###subset dataframe by species/ layer##

elev1969withzerosOTV<-tryOTV%>%filter(Year=="1969")
elev2015withzerosOTV<-tryOTV%>%filter(Year=="2015")

dist_dat_split1969_withzerosOTV<-split.data.frame(x = elev1969withzerosOTV,f = elev1969withzerosOTV$SPECIES)
dist_dat_split2015_withzerosOTV<-split.data.frame(x = elev2015withzerosOTV,f = elev2015withzerosOTV$SPECIES)


## wilcoxon signed rank tests for layer #####
wilcoxbylayerteststatOTV<-as.data.frame(stack(mapply(function(x, y) wilcox.test(x$OTV,y$OTV, paired=TRUE)$statistic, dist_dat_split1969_withzerosOTV, dist_dat_split2015_withzerosOTV)))

wilcoxbylayertestpvalOTV<-as.data.frame(stack(mapply(function(x, y) wilcox.test(x$OTV,y$OTV, paired=TRUE)$p.value, dist_dat_split1969_withzerosOTV, dist_dat_split2015_withzerosOTV)))

testsOTV<-mapply(function(x, y) wilcox.test(x$OTV,y$OTV, paired=TRUE), dist_dat_split1969_withzerosOTV, dist_dat_split2015_withzerosOTV)

wilcoxbylayertestpvalOTV$values<-round(wilcoxbylayertestpvalOTV$values,6)

#####we've run four tests (seedlings, saplings, canopy, and sum total), so let's use the adjustment of 0.05/4 = 0.0125 for significance (two asterisks) and 0.1/4 = 0.025 for marginal significance (one asterisk). 

wilcoxbylayertestpvalOTV <- data.table(wilcoxbylayertestpvalOTV)
wilcoxbylayertestpvalOTV$signif <- ifelse(wilcoxbylayertestpvalOTV$values < 0.0125,"significant","not significant")

```



```{r Wilcoxon tests total canopy cover COVER}


totalcover_1969<-subset(totalcover_long, YEAR==1969)
totalcover_2015<-subset(totalcover_long, YEAR==2015)


# split the dataframe by species##

total_dist_dat_split1969Cover<-split.data.frame(x = totalcover_1969,f = totalcover_1969$SPECIES)
total_dist_dat_split2015Cover<-split.data.frame(x = totalcover_2015,f =totalcover_2015$SPECIES)




## wilcoxon signed rank tests for total cover #####
wilcoxteststat<-as.data.frame(stack(mapply(function(x, y) wilcox.test(x$TotalCover,y$TotalCover, paired=TRUE)$statistic, total_dist_dat_split1969Cover, total_dist_dat_split2015Cover)))

wilcoxtestpval<-as.data.frame(stack(mapply(function(x, y) wilcox.test(x$TotalCover,y$TotalCover, paired=TRUE)$p.value, total_dist_dat_split1969Cover, total_dist_dat_split2015Cover)))

wilcoxtestpval$values<-round(wilcoxtestpval$values,4)




```



```{r Wilcoxon tests total canopy cover OTV}


totalOTV_1969<-subset(totalOTV_long2, YEAR==1969)
totalOTV_2015<-subset(totalOTV_long2, YEAR==2015)


# split the dataframe by species##

total_dist_dat_split1969OTV<-split.data.frame(x = totalOTV_1969,f = totalOTV_1969$SPECIES)
total_dist_dat_split2015OTV<-split.data.frame(x = totalOTV_2015,f =totalOTV_2015$SPECIES)




## wilcoxon signed rank tests for total cover #####
wilcoxteststatOTV<-as.data.frame(stack(mapply(function(x, y) wilcox.test(x$TotalOTV,y$TotalOTV, paired=TRUE)$statistic, total_dist_dat_split1969OTV, total_dist_dat_split2015OTV)))

wilcoxtestpvalOTV<-as.data.frame(stack(mapply(function(x, y) wilcox.test(x$TotalOTV,y$TotalOTV, paired=TRUE)$p.value, total_dist_dat_split1969OTV, total_dist_dat_split2015OTV)))

wilcoxtestpvalOTV$values<-round(wilcoxtestpvalOTV$values,4)




```



```{r elevation violin plots by layer}

mytheme<- theme_bw()+ theme(axis.line.x= element_line(colour = "black", size=0.3))+theme(axis.line.y= element_line(colour = "black", size=0.3))+theme(axis.text.x=element_text(size=8, colour = "black"))+theme(axis.text.y=element_text(size=8, colour = "black"))+theme(axis.title=element_text(size=12))+theme(plot.title=element_text(size=6) +theme(plot.title = element_text(hjust = 0.5)))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ theme(legend.position = "none")+ theme(strip.background = element_blank()) + theme(strip.text = element_text(face = "italic"))


dodge <- position_dodge(width = 0.8)

Elevbylayer<-ggplot(aes(x = LAYER, y = ELEV),data = dist_dat2)+   geom_violin(position=dodge, trim=TRUE, alpha=0.7, aes(fill=Year)) + geom_boxplot(width=0.2,lwd=0.3, position=dodge,outlier.color=NA, aes(color=Year))+
  facet_wrap(~SPECIES2,nrow = 4, ncol = 3) + 
  mytheme +
  ylab("Elevation (m)") +
  xlab("")+
  ylim(1000,2500)+
  theme(strip.text = element_text(size=9.5))+
  theme(panel.grid.minor = element_line(colour = "grey", size = 0.5))+ 
  theme(panel.grid.major.y  = element_line(colour = "grey", size = 0.5))+
  scale_y_continuous(limits=c(1200, 2500), breaks=seq(1200,2500,300))+
  scale_fill_manual(values=c("gray30", "green4"))+
  scale_color_manual(values=c("black", "black"))+
  theme(legend.position="right")+
  theme(legend.title = element_blank())
  

### to export...add in file path where you want to save ##

jpeg("C:/Users/Mitzi/Desktop/Collaborations/Sugar Creek Aug 2020/elev_violin_layer.jpeg",width = 6, height = 5,units = 'in', res = 600)
Elevbylayer
dev.off()


```



```{r HLI violin plots by layer}

mytheme<- theme_bw()+ theme(axis.line.x= element_line(colour = "black", size=0.3))+theme(axis.line.y= element_line(colour = "black", size=0.3))+theme(axis.text.x=element_text(size=8, colour = "black"))+theme(axis.text.y=element_text(size=8, colour = "black"))+theme(axis.title=element_text(size=12))+theme(plot.title=element_text(size=6) +theme(plot.title = element_text(hjust = 0.5)))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ theme(legend.position = "none")+ theme(strip.background = element_blank()) + theme(strip.text = element_text(face = "italic"))


HLIbylayer<-ggplot(aes(x = LAYER, y = HLI,fill = Year,),data = dist_dat2) +
  geom_violin(position=position_dodge(),trim=TRUE) +
  facet_wrap(~SPECIES2,nrow = 4, ncol = 3) + 
  mytheme +
  ylab("Heat load index") +
  xlab("")+
  scale_fill_manual(values=alpha(c("gray30", "green4"), 0.7))+
  theme(strip.text = element_text(size=9.5))+
  theme(panel.grid.minor = element_line(colour = "grey", size = 0.5))+ 
  theme(panel.grid.major.y  = element_line(colour = "grey", size = 0.5))+
  theme(legend.position="right")+
  theme(legend.title = element_blank())

HLIbylayer<-ggplot(aes(x = LAYER, y =HLI),data = dist_dat2)+   geom_violin(position=dodge, trim=TRUE, alpha=0.7, aes(fill=Year)) + geom_boxplot(width=0.2,lwd=0.3, position=dodge,outlier.color=NA, aes(color=Year))+
  facet_wrap(~SPECIES2,nrow = 4, ncol = 3) + 
  mytheme +
  ylab("Heat load index") +
  xlab("")+
  theme(strip.text = element_text(size=9.5))+
  theme(panel.grid.minor = element_line(colour = "grey", size = 0.5))+ 
  theme(panel.grid.major.y  = element_line(colour = "grey", size = 0.5))+
  scale_fill_manual(values=c("gray30", "green4"))+
  scale_color_manual(values=c("black", "black"))+
  ylim(c(0.25,1))+
  theme(legend.position="right")+
  theme(legend.title = element_blank())



### to export...add in file path where you want to save ##

jpeg("C:/Users/Mitzi/Desktop/Collaborations/Sugar Creek Aug 2020/HLI_violin_layer.jpeg",width = 6, height = 5,units = 'in', res = 600)
HLIbylayer
dev.off()


```




```{r plot canopy cover by layer}

mytheme<- theme_bw()+ theme(axis.line.x= element_line(colour = "black", size=0.3))+theme(axis.line.y= element_line(colour = "black", size=0.3))+theme(axis.text.x=element_text(size=8, colour = "black"))+theme(axis.text.y=element_text(size=8, colour = "black"))+theme(axis.title=element_text(size=12))+theme(plot.title=element_text(size=6) +theme(plot.title = element_text(hjust = 0.5)))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ theme(legend.position = "none")+ theme(strip.background = element_blank()) + theme(strip.text = element_text(face = "italic"))


##add stars for significance in paint##

##

coverbylayer<-ggplot(aes(x = LAYER, y = meancover,fill = Year,),data = avgcoverbylayerdf) +
  geom_bar(stat="identity",position=position_dodge()) +
  geom_errorbar(aes(ymin=meancover-secover, ymax=meancover+secover), width=.2,position=position_dodge(.9))+
  facet_wrap(~SPECIES2,nrow = 3, ncol = 4)+
  ylab("Cover (%)") +
  xlab("")+
  scale_fill_manual(values=alpha(c("gray30", "green4"), 1))+
  theme(strip.text = element_text(size=9.5))+
  theme(panel.grid.minor = element_line(colour = "grey", size = 0.5))+ 
  theme(panel.grid.major.y  = element_line(colour = "grey", size = 0.5))+
  scale_y_continuous(limits=c(0, 30), breaks=seq(0,30,10))+
  theme(legend.position="right")+
  theme(legend.title = element_blank())+
  mytheme


##

jpeg("C:/Users/Mitzi/Desktop/Collaborations/Sugar Creek Aug 2020/coverby_layer.jpeg",width = 6, height = 5,units = 'in', res = 600)
coverbylayer
dev.off()





```



```{r plot canopy cover total}

mytheme<- theme_bw()+ theme(axis.line.x= element_line(colour = "black", size=0.3))+theme(axis.line.y= element_line(colour = "black", size=0.3))+theme(axis.text.x=element_text(size=8, colour = "black"))+theme(axis.text.y=element_text(size=8, colour = "black"))+theme(axis.title=element_text(size=12))+theme(plot.title=element_text(size=6) +theme(plot.title = element_text(hjust = 0.5)))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ theme(legend.position = "none")+ theme(strip.background = element_blank()) + theme(strip.text = element_text(face = "italic"))


###species names###
avgcovertotaldf2<-avgcovertotaldf%>%mutate(SPECIES2 = SPECIES)
avgcovertotaldf2$SPECIES2<-plyr::mapvalues(avgcovertotaldf2$SPECIES2, from=c("ABCO", "ABLAS", "ABMA", "CADE", "PIBR", "PICO", "PIEN", "PILA", "PIMO", "PIPO", "PSME", "TSME"), to=c("Abies concolor", "Abies lasiocarpa", "Abies magnifica", "Calocedrus decurrens", "Picea breweriana", "Picea engelmannii", "Pinus contorta","Pinus lambertiana","Pinus monticola", "Pinus ponderosa", "Pseudotsuga menziesii", "Tsuga mertensiana"))


covertotal<-ggplot(aes(x = SPECIES2, y = meancover,fill = Year,),data = avgcovertotaldf2) +
  geom_bar(stat="identity",position=position_dodge()) +
  geom_errorbar(aes(ymin=meancover-secover, ymax=meancover+secover), width=.2,position=position_dodge(.9))+
  mytheme +
  ylab("Total Cover (%)") +
  xlab("")+
  scale_fill_manual(values=alpha(c("gray30", "green4"), 1))+
  theme(strip.text = element_text(size=9.5))+
  theme(panel.grid.minor = element_line(colour = "grey", size = 0.5))+ 
  theme(panel.grid.major.y  = element_line(colour = "grey", size = 0.5))+
  scale_y_continuous(limits=c(0, 30), breaks=seq(0,30,10))+
  theme(legend.position="right")+
  theme(legend.title = element_blank())+
  theme(legend.key.size = unit(0.5, 'cm'))+
  theme(axis.text.x=element_text(angle=50, face="italic",hjust = 1))


jpeg("C:/Users/Mitzi/Desktop/Collaborations/Sugar Creek Aug 2020/totalcover.jpeg",width = 5, height = 3,units = 'in', res = 600)
covertotal
dev.off()

```




```{r plot ABCO variability bands}

mytheme<- theme_bw()+ theme(axis.line.x= element_line(colour = "black", size=0.3))+theme(axis.line.y= element_line(colour = "black", size=0.3))+theme(axis.text.x=element_text(size=8, colour = "black"))+theme(axis.text.y=element_text(size=8, colour = "black"))+theme(axis.title=element_text(size=12))+theme(plot.title=element_text(size=14) +theme(plot.title = element_text(hjust = 0.5)))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ theme(legend.position = "none")+ theme(strip.background = element_blank()) + theme(strip.text = element_text(face = "italic"))

head(ABCOcan)

ABCOcan$Year<-as.factor(as.character(ABCOcan$Year))


ABCOcoverelev<-ggplot(aes(x = as.numeric(Elevation2015m), y = Estim,color= Year, fill = Year),data = ABCOcan) +
  geom_point() +
  geom_ribbon(aes(ymin=LowBand, ymax=HighBand), color=NA, alpha=0.2)+
  mytheme +
  ylab("Canopy Cover (%)") +
  xlab("Elevation (m)")+
  annotate(geom="text", x=2300, y=55, label="Abies concolor", size=4, fontface = "italic")+
  scale_color_manual(values=alpha(c("gray30", "green4"), 1))+
  scale_fill_manual(values=alpha(c("gray30", "green4"), 1))+
  theme(legend.position=c(0.76, 0.75))+
  theme(legend.title = element_blank())+
  theme(legend.key.size = unit(0.7, 'cm'))


jpeg("C:/Users/Mitzi/Desktop/Academic Collaborations/Sugar Creek Aug 2020/ABCOvariability.jpeg",width = 4, height = 3,units = 'in', res = 600)
ABCOcoverelev
dev.off()

```


```{r climate variables}

head(bcm_plot19592014_3)

##count months per plot per year##

countmonths<-bcm_plot19592014_3 %>% count(ID, wyear)

####

precipdata<-bcm_plot19592014_3 %>% group_by(ID, wyear, ELEV, HLI) %>% dplyr::summarise(yearlyppt=sum(ppt, na.rm=FALSE))

tmndata<-bcm_plot19592014_3 %>% group_by(ID, Year) %>% dplyr::summarise(tempmin=min(tmn, na.rm=FALSE))

growingseasondata<-bcm_plot19592014_3 %>% filter(Month=="Jun"|Month=="Jul"|Month=="Aug")%>% group_by(ID, Year) %>% dplyr::summarise(gsmax=max(tmx, na.rm=FALSE))

cwddata<-bcm_plot19592014_3 %>% group_by(ID, Year) %>% dplyr::summarise(yearlycwd=sum(cwd, na.rm=FALSE))

####

allclimate<-cbind(precipdata,tempmin=tmndata$tempmin, gsmax=growingseasondata$gsmax, cwd=cwddata$yearlycwd)

###1960s avg###


climate1960s_1<-allclimate %>% filter(wyear>1959 & wyear < 1970)%>% group_by(ID, ELEV, HLI) %>% dplyr::summarise(precip1960s=mean(yearlyppt, na.rm=FALSE), tempmin1960s=mean(tempmin, na.rm=FALSE), gsmax1960s=mean(gsmax, na.rm=FALSE), cwd1960s=mean(cwd, na.rm=FALSE), n=n())

climate1960s_2<-allclimate %>% filter(wyear>1959 & wyear < 1970)%>% group_by(ID, ELEV, HLI) %>% dplyr::summarise(precip1960s=mean(yearlyppt, na.rm=TRUE), tempmin1960s=mean(tempmin, na.rm=TRUE), gsmax1960s=mean(gsmax, na.rm=TRUE), cwd1960s=mean(cwd, na.rm=TRUE), n=n())

##2000s average##

climate2000s<-allclimate %>% filter(wyear>2004 & wyear < 2015)%>% group_by(ID, ELEV, HLI) %>% dplyr::summarise(precip2000s=mean(yearlyppt, na.rm=TRUE), tempmin2000s=mean(tempmin, na.rm=TRUE), gsmax2000s=mean(gsmax, na.rm=TRUE), cwd2000s=mean(cwd, na.rm=TRUE), n=n())

climate2000s_2<-as.data.frame(climate2000s[,4:7])

climate1960s_2<-as.data.frame(climate1960s)
####

climate1960s2000s_2<-cbind(climate1960s_2, climate2000s_2)


###
climate1960s2000s_2$diffprecip=climate1960s2000s_2$precip2000s-climate1960s2000s_2$precip1960s

climate1960s2000s_2$difftempmin=climate1960s2000s_2$tempmin2000s-climate1960s2000s_2$tempmin1960s

climate1960s2000s_2$diffgsmax=climate1960s2000s_2$gsmax2000s-climate1960s2000s_2$gsmax1960s

climate1960s2000s_2$diffcwd=climate1960s2000s_2$cwd2000s-climate1960s2000s_2$cwd1960s


##relative diff##

climate1960s2000s_2$reldiffprecip=(climate1960s2000s_2$diffprecip/climate1960s2000s_2$precip1960s)*100

climate1960s2000s_2$reldifftempmin=(climate1960s2000s_2$difftempmin/climate1960s2000s_2$tempmin1960s)*100

climate1960s2000s_2$reldiffgsmax=(climate1960s2000s_2$diffgsmax/climate1960s2000s_2$gsmax1960s*100)

climate1960s2000s_2$reldiffcwd=(climate1960s2000s_2$diffcwd/climate1960s2000s_2$cwd1960s)*100

###is regression significant?##

modelprecip<-lm(diffprecip~ELEV+HLI, data=climate1960s2000s_2)
modelGStemp<-lm(diffgsmax~ELEV+HLI, data=climate1960s2000s_2)
modelmintemp<-lm(difftempmin~ELEV+HLI, data=climate1960s2000s_2)
modelCWD<-lm(diffcwd~ELEV+HLI, data=climate1960s2000s_2)

####

mytheme<- theme_bw()+ theme(axis.line.x= element_line(colour = "black", size=0.3))+theme(axis.line.y= element_line(colour = "black", size=0.3))+theme(axis.text.x=element_text(size=10, colour = "black"))+theme(axis.text.y=element_text(size=10, colour = "black"))+theme(axis.title=element_text(size=12))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())



diffprecipplot<-ggplot(aes(x = ELEV, y = diffprecip, color=HLI),data = climate1960s2000s_2) +
  geom_point() +
  mytheme +
  geom_smooth(method='lm', formula= y~x, color="black")+
  ylim(-150, 150)+
  xlim(1200, 2600)+
  ylab(expression(atop("Change in precipitation (mm)", paste("2000s - 1960s"))))+
  xlab("Elevation (m)")+
  scale_colour_viridis()




diffwinterminplot<-ggplot(aes(x = ELEV, y = difftempmin, color=HLI),data = climate1960s2000s_2) +
  geom_point() +
  mytheme +
  geom_smooth(method='lm', formula= y~x, color="black")+
  xlim(1200, 2600)+
  ylim(1.0, 2.6)+
  ylab(expression(atop("Change in min temp(C)", paste("2000s - 1960s"))))+
  xlab("Elevation (m)")+
  scale_colour_viridis()


diffgsmaxplot<-ggplot(aes(x = ELEV, y = diffgsmax, color=HLI),data = climate1960s2000s_2) +
  geom_point() +
  geom_smooth(method='lm', formula= y~x, color="black")+
  mytheme +
  xlim(1200, 2600)+
  ylim(-0.5, 1.7)+
  ylab(expression(atop("Change in max GS temp (C)", paste("2000s - 1960s"))))+
  xlab("Elevation (m)")+
  scale_colour_viridis()

diffCWDplot<-ggplot(aes(x = ELEV, y = diffcwd, color=HLI),data = climate1960s2000s_2) +
  geom_point() +
  xlim(1200, 2600)+
  ylim(-100, 10)+
  geom_smooth(method='lm', formula= y~x, color="black")+
  mytheme +
  ylab(expression(atop("Change in CWD (mm H2O)", paste("2000s - 1960s"))))+
  xlab("Elevation (m)")+
  scale_colour_viridis()

##combine plots###

multiplot(diffprecipplot, diffwinterminplot, diffgsmaxplot,  diffCWDplot, cols=2)

jpeg("C:/Users/Mitzi/Desktop/Academic Collaborations/Sugar Creek Aug 2020/climatediffraw.jpeg",width = 8, height = 6,units = 'in', res = 600)
multiplot(diffprecipplot, diffwinterminplot, diffgsmaxplot,  diffCWDplot, cols=2)
dev.off()


####


```

