---
title: "Cover_elevation_stats_fig"
author: "Melissa DeSiervo" mhdesiervo@gmail.com, mdesierv@uwyo.edu
date: "4/7/2021"
output: html_document
---

library(vegan)
library(indicspecies)
library(tidyverse)
library(data.table)
library(ggplot2)
library(gplots)
library(rcompanion)
library(betapart)
library(weights)
library(stringr)
library(viridis)
library(SciViews)
library(here)



```{r import site and tree data, include=FALSE}

###import files tree data and site data##


###reed in long tree data###
tree_long <- read.csv(here("SAWYER/rawdata/tree_long.csv"), header=T)


##create new columns with PLOT YEAR and SPECIES LAYER###

tree_long2<-tree_long %>% mutate(PLOTYEAR= paste0(Plot, Year))%>% mutate(SPECIES2= paste0(SpeciesCode, layer2))

###create new column with OTV transformation###

tree_long3<-tree_long2 %>% mutate(OTV = 1.415*log(Cover) + 2)

###another column with transformed back to % from OTV##


tree_long4<-tree_long3 %>% mutate(logcover = (OTV-2)/1.415) %>% mutate(coverOTV=exp(logcover))


####Site X Species matrix with Cover###

tree_long4<-tree_long3 %>% select(PLOTYEAR, SPECIES2, Cover)

tree.wideCover <- reshape(tree_long4, idvar = "PLOTYEAR", timevar = "SPECIES2", direction = "wide")

names(tree.wideCover) <- gsub("Cover.", "", names(tree.wideCover))

# Fill in NA's with zeros in wide data set
tree.wideCover[is.na(tree.wideCover)] <- 0


####Site X Species matrix with OTV###

tree_long5<-tree_long3 %>% select(PLOTYEAR, SPECIES2, OTV)

tree.wideOTV <- reshape(tree_long5, idvar = "PLOTYEAR", timevar = "SPECIES2", direction = "wide")

names(tree.wideOTV) <- gsub("Cover.", "", names(tree.wideCover))

tree.wideOTV[is.na(tree.wideOTV)] <- 0

####Number of plotyears (292), matches the old file we had###


##read in table with env data
env_imp <- read.csv(here("SAWYER/rawdata/sitedata.csv"), header=T)


#make year a factor
env_imp$Year<-as.factor(env_imp$Year)


###merge env and sp data cover
all_datCover<-merge(tree.wideCover, env_imp, by="PLOTYEAR")

all_datOTV<-merge(tree.wideOTV, env_imp, by="PLOTYEAR")


ABCOcan <- read.csv(here("SAWYER/rawdata/ABCO_CAN.csv"), header=T)


##read in ABCO variability band data from PcORD ###
#ABCOcan<-read.csv(here("SAWYER/rawdata/ABCO_CAN.csv", header=TRUE))


```



```{r import climate data, include=FALSE}


##read in wide plot-level BCM (downscaled climate data) ##
#plotbcm_wide<-read.csv("C:/Users/Melissa/Dropbox/Sugar Creek Aug 2020/Plot_BCM_WaterYear_Monthly_wide.csv", header=TRUE)

#covert to long##
#plotbcm_long <- gather(plotbcm_wide, ID, measurement, A01:C05, factor_key=TRUE)

##then make weather variables wide###

#plotbcm2 <- spread(plotbcm_long, Var, measurement)

######merge the plot bcm with the env attributes of plots#####

#env_imp2<-env_imp %>% select(ID, Easting, Northing, ELEV, HLI, TPI_25)

#bcm_plot<-merge(plotbcm2, env_imp2, by="ID")

##filter to the years of interest###


#bcm_plot$Year

#bcm_plot19592014<-subset(bcm_plot, Year > 1957)

##remove duplicates##

#bcm_plot19592014_2<-unique(bcm_plot19592014)

#bcm_plot19592014_2$Month <- factor(bcm_plot19592014_2$Month, levels = c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"))

##add column water year## (so that Oct - Sept = one precipitation season)

#bcm_plot19592014_3<-bcm_plot19592014_2 %>% mutate(wyear = ifelse(Month=="Oct"|Month=="Nov"|Month=="Dec", Year, Year-1))%>%select(ID, Year, wyear, Month, ELEV, HLI, Easting, Northing, aet, cwd, pck, pet, ppt, tmn, tmx)


```



```{r sum up layers for total cover and total OTV, echo=FALSE}

########sum strata by species
##abco
tree.wideCover$ABCO<-tree.wideCover$ABCOCAN +tree.wideCover$ABCOSAP+tree.wideCover$ABCOSEED
##ablas
tree.wideCover$ABLAS<-tree.wideCover$ABLASCAN +tree.wideCover$ABLASSAP+tree.wideCover$ABLASSEED
##abma
tree.wideCover$ABMA<-tree.wideCover$ABMACAN+tree.wideCover$ABMASAP+tree.wideCover$ABMASEED
##cade
tree.wideCover$CADE<-tree.wideCover$CADECAN+tree.wideCover$CADESAP+tree.wideCover$CADESEED
##picbre
tree.wideCover$PIBR<-tree.wideCover$PICBRECAN+tree.wideCover$PICBRESAP+tree.wideCover$PICBRESEED
##piceng
tree.wideCover$PIEN<-tree.wideCover$PICENGCAN+tree.wideCover$PICENGSAP+tree.wideCover$PICENGSEED
##pincon
tree.wideCover$PICO<-tree.wideCover$PINCONCAN+tree.wideCover$PINCONSAP+tree.wideCover$PINCONSEED
##pinlam
tree.wideCover$PILA<-tree.wideCover$PINLAMCAN+tree.wideCover$PINLAMSAP+tree.wideCover$PINLAMSEED
##pinmon
tree.wideCover$PIMO<-tree.wideCover$PINMONCAN+tree.wideCover$PINMONSAP+tree.wideCover$PINMONSEED
##pinpon
tree.wideCover$PIPO<-tree.wideCover$PINPONCAN+tree.wideCover$PINPONSAP+tree.wideCover$PINPONSEED
##psme
tree.wideCover$PSME<-tree.wideCover$PSMECAN+tree.wideCover$PSMESAP+tree.wideCover$PSMESEED
##tsme
tree.wideCover$TSME<-tree.wideCover$TSMERCAN+tree.wideCover$TSMERSAP+tree.wideCover$TSMERSEED

####

totalcover<-tree.wideCover %>% select(PLOTYEAR, ABCO:TSME)

totalcover_2<-separate(data = totalcover, col = PLOTYEAR, into = c("PLOT", "YEAR"), sep=3, remove=FALSE)

totalcover_long <- gather(totalcover_2, SPECIES, TotalCover, ABCO:TSME, factor_key=TRUE)


avgcovertotal<-totalcover_long %>% group_by(YEAR, SPECIES) %>% dplyr::summarise(meancover=mean(TotalCover, na.rm=TRUE),sdcover=sd(TotalCover, na.rm=TRUE),secover=sd(TotalCover, na.rm=TRUE)/sqrt(n()))


##converting total cover into OTV###


totalcover_longOTV<-totalcover_long %>% mutate(TotalOTV = 1.415*log(TotalCover) + 2)

totalcover_longOTV$TotalOTV[!is.finite(totalcover_longOTV$TotalOTV)] <- 0  ##make infint values 0##





```


```{r weighted mean elevations total cover and OTV}

###merge env and sp data cover
totalcover_long3<-merge(totalcover_long, env_imp, by="PLOTYEAR")


totalcover_1969<-subset(totalcover_long3, YEAR==1969)
totalcover_2015<-subset(totalcover_long3, YEAR==2015)


# split the dataframe by species##

total_dist_dat_split1969Cover<-split.data.frame(x = totalcover_1969,f = totalcover_1969$SPECIES)
total_dist_dat_split2015Cover<-split.data.frame(x = totalcover_2015,f =totalcover_2015$SPECIES)



### weighted elevation averages###
weightedmean1969COVER<-stack(lapply(X = total_dist_dat_split1969Cover,function(t){
  means1969<-weighted.mean(t$ELEV, t$TotalCover)
  return(means1969)
}
))
 
weightedmean2015COVER<-stack(lapply(X = total_dist_dat_split2015Cover,function(t){
  means2015<-weighted.mean(t$ELEV, t$TotalCover)
  return(means2015)
}
))


#####OTV########

totalcover_longOTV3<-merge(totalcover_longOTV, env_imp, by="PLOTYEAR")


totalcoverOTV_1969<-subset(totalcover_longOTV3, YEAR==1969)
totalcoverOTV_2015<-subset(totalcover_longOTV3, YEAR==2015)


# split the dataframe by species##

total_dist_dat_split1969OTV<-split.data.frame(x = totalcoverOTV_1969,f = totalcover_1969$SPECIES)
total_dist_dat_split2015OTV<-split.data.frame(x = totalcoverOTV_2015,f =totalcover_2015$SPECIES)



### weighted elevation averages###
weightedmean1969OTV<-stack(lapply(X = total_dist_dat_split1969OTV,function(t){
  means1969<-weighted.mean(t$ELEV, t$TotalOTV)
  return(means1969)
}
))
 
weightedmean2015OTV<-stack(lapply(X = total_dist_dat_split2015OTV,function(t){
  means2015<-weighted.mean(t$ELEV, t$TotalOTV)
  return(means2015)
}
))

weightedmeans<-as.data.frame(cbind(species=as.factor(as.character(weightedmean1969OTV$ind,2)), elev1969=round(weightedmean1969OTV$values,2), elev2015=round(weightedmean2015OTV$values)))

weightedmeans2<-weightedmeans %>% mutate(elevdiff=elev2015-elev1969) %>% mutate(elevdiffdecade=elevdiff/(2015-1969)*10)

###these results are first few columns in Table 2####





```



```{r weighted mean t tests total cover}

###merge env and sp data cover
totalcover_long3<-merge(totalcover_long, env_imp, by="PLOTYEAR")


totalcover_1969<-subset(totalcover_long3, YEAR==1969)
totalcover_2015<-subset(totalcover_long3, YEAR==2015)


# split the dataframe by species##

total_dist_dat_split1969Cover<-split.data.frame(x = totalcover_1969,f = totalcover_1969$SPECIES)
total_dist_dat_split2015Cover<-split.data.frame(x = totalcover_2015,f =totalcover_2015$SPECIES)


## weighted t test for elevation#####


###doing it manually works....##


wtd.t.test(total_dist_dat_split1969Cover[[1]]$ELEV,total_dist_dat_split2015Cover[[1]]$ELEV, weight=as.numeric(total_dist_dat_split1969Cover[[1]]$TotalCover), weighty=as.numeric(total_dist_dat_split2015Cover[[1]]$TotalCover))$coefficients




```



```{weighted t tests elevation by layer COVER}

#####COVER########

tree_longplot<-merge(tree_long3, env_imp[3:6], by="PLOTYEAR")

tree_longplot$ELEV<-as.numeric(tree_longplot$ELEV)

###subset dataframe by species/ layer##

elev1969Cover<-tree_longplot%>%filter(Year=="1969")%>%filter(Cover>0)
elev2015Cover<-tree_longplot%>%filter(Year=="2015")%>%filter(Cover>0)

## split the dataframe by species / layer##

dist_dat_split1969Cover<-split.data.frame(x = elev1969Cover,f = elev1969Cover$SPECIES2)

dist_dat_split2015Cover<-split.data.frame(x = elev2015Cover,f = elev2015Cover$SPECIES2)

## weighted t test for elevation#####


weightedttests2<-mapply(x = split.data.frame(x = elev1969Cover,f = elev1969Cover$SPECIES2),y = split.data.frame(x = elev2015Cover,f = elev2015Cover$SPECIES2),function(x,y){
  z<-wtd.t.test(x$ELEV, y$ELEV, weight=x$Cover, weighty=y$Cover, samedata=FALSE)$coefficients
  return(data.frame(z))
})




### weighted elevation averages###
weightedmean1969COVER<-stack(lapply(X = dist_dat_split1969Cover,function(t){
  means1969<-weighted.mean(t$ELEV, t$Cover)
  return(means1969)
}
))
 
weightedmean2015COVER<-stack(lapply(X = dist_dat_split2015Cover,function(t){
  means2015<-weighted.mean(t$ELEV, t$Cover)
  return(means2015)
}
))


#####OTV########



### weighted elevation averages###
weightedmean1969OTV<-stack(lapply(X = dist_dat_split1969Cover,function(t){
  means1969<-weighted.mean(t$ELEV, t$OTV)
  return(means1969)
}
))
 
weightedmean2015OTV<-stack(lapply(X = dist_dat_split2015Cover,function(t){
  means2015<-weighted.mean(t$ELEV, t$OTV)
  return(means2015)
}
))


```



```{weighted t tests elevation by layer OTV}

#####OTV########

tree_longplot<-merge(tree_long3, env_imp[3:6], by="PLOTYEAR")

tree_longplot$ELEV<-as.numeric(tree_longplot$ELEV)

X1969 = split.data.frame(x = elev1969Cover,f = elev1969Cover$SPECIES2)

Y2015 = split.data.frame(x = elev2015Cover,f = elev2015Cover$SPECIES2)

####
weightedttestsOTV<-mapply(x = split.data.frame(x = elev1969Cover,f = elev1969Cover$SPECIES2),y = split.data.frame(x = elev2015Cover,f = elev2015Cover$SPECIES2),function(x,y){
  z<-wtd.t.test(x$ELEV, y$ELEV, weight=x$OTV, weighty=y$OTV, samedata=FALSE)$coefficients
  return(data.frame(z))
})

###manual way of extracting values###


wtd.t.test(X1969[[1]]$ELEV, Y2015[[1]]$ELEV, weight=X1969[[1]]$OTV, weighty=Y2015[[1]]$OTV, samedata=FALSE)


###values in table###



## split the dataframe by species / layer##

dist_dat_split1969OTV<-split.data.frame(x = elev1969Cover,f = elev1969Cover$SPECIES2)

dist_dat_split2015OTV<-split.data.frame(x = elev2015Cover,f = elev2015Cover$SPECIES2)



### weighted elevation averages OTV ###
weightedmean1969OTV<-stack(lapply(X = dist_dat_split1969Cover,function(t){
  means1969<-weighted.mean(t$ELEV, t$OTV)
  return(means1969)
}
))

weightedmean1969OTVdf<-as.data.frame(weightedmean1969OTV)
 
weightedmean2015OTV<-stack(lapply(X = dist_dat_split2015Cover,function(t){
  means2015<-weighted.mean(t$ELEV, t$OTV)
  return(means2015)
}
))

weightedmean1969OTVdf<-as.data.frame(weightedmean1969OTV)
weightedmean2015OTVdf<-as.data.frame(weightedmean2015OTV)

###

weightedmeans<-as.data.frame(cbind(elev1969ls = weightedmean1969OTVdf$values,elev2015ls = weightedmean2015OTVdf$values))

weightedmeans2<-weightedmeans %>% mutate(diff=elev2015ls-elev1969ls) 

##values for table 



```





```{r Wilcoxon tests canopy cover by layer COVER}


##wilcox signed rank tests by layer##

try<-gather(all_datCover, SPECIES,Cover, ABCOCAN:TSMERSEED) ##keep the zeroes##
try$SPECIES<-as.factor(try$SPECIES)

###subset dataframe by species/ layer##

elev1969withzeros<-try%>%filter(Year=="1969")
elev2015withzeros<-try%>%filter(Year=="2015")

dist_dat_split1969_withzeros<-split.data.frame(x = elev1969withzeros,f = elev1969withzeros$SPECIES)
dist_dat_split2015_withzeros<-split.data.frame(x = elev2015withzeros,f = elev2015withzeros$SPECIES)


## wilcoxon signed rank tests for layer #####
wilcoxbylayerteststat<-as.data.frame(stack(mapply(function(x, y) wilcox.test(x$Cover,y$Cover, paired=TRUE)$statistic, dist_dat_split1969_withzeros, dist_dat_split2015_withzeros)))

wilcoxbylayertestpval<-as.data.frame(stack(mapply(function(x, y) wilcox.test(x$Cover,y$Cover, paired=TRUE)$p.value, dist_dat_split1969_withzeros, dist_dat_split2015_withzeros)))

tests<-mapply(function(x, y) wilcox.test(x$Cover,y$Cover, paired=TRUE), dist_dat_split1969_withzeros, dist_dat_split2015_withzeros)

wilcoxbylayertestpval$values<-round(wilcoxbylayertestpval$values,6)

#####we've run four tests (seedlings, saplings, canopy, and sum total), so let's use the adjustment of 0.05/4 = 0.0125 for significance (two asterisks) and 0.1/4 = 0.025 for marginal significance (one asterisk). 

wilcoxbylayertestpval <- data.table(wilcoxbylayertestpval)
wilcoxbylayertestpval$signif <- ifelse(wilcoxbylayertestpval$values < 0.0125,"significant","not significant")

```




```{r Wilcoxon tests total canopy cover COVER}


totalcover_1969<-subset(totalcover_long, YEAR==1969)
totalcover_2015<-subset(totalcover_long, YEAR==2015)


# split the dataframe by species##

total_dist_dat_split1969Cover<-split.data.frame(x = totalcover_1969,f = totalcover_1969$SPECIES)
total_dist_dat_split2015Cover<-split.data.frame(x = totalcover_2015,f =totalcover_2015$SPECIES)




## wilcoxon signed rank tests for total cover #####
wilcoxteststat<-as.data.frame(stack(mapply(function(x, y) wilcox.test(x$TotalCover,y$TotalCover, paired=TRUE)$statistic, total_dist_dat_split1969Cover, total_dist_dat_split2015Cover)))

wilcoxtestpval<-as.data.frame(stack(mapply(function(x, y) wilcox.test(x$TotalCover,y$TotalCover, paired=TRUE)$p.value, total_dist_dat_split1969Cover, total_dist_dat_split2015Cover)))

wilcoxtestpval$values<-round(wilcoxtestpval$values,4)




```




```{r plot elevation violin by layer}

##elevation OTV use tree_long3 ###



elevationlongOTV<-merge(tree_long3, env_imp, by=c("PLOTYEAR", "Plot", "Year"))


elevationlongOTV$Year<-as.factor(elevationlongOTV$Year)

mytheme<- theme_bw()+ theme(axis.line.x= element_line(colour = "black", size=0.3))+theme(axis.line.y= element_line(colour = "black", size=0.3))+theme(axis.text.x=element_text(size=8, colour = "black"))+theme(axis.text.y=element_text(size=8, colour = "black"))+theme(axis.title=element_text(size=12))+theme(plot.title=element_text(size=6) +theme(plot.title = element_text(hjust = 0.5)))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ theme(legend.position = "none")+ theme(strip.background = element_blank()) + theme(strip.text = element_text(face = "italic"))


dodge <- position_dodge(width = 0.8)

Elevbylayer<-ggplot(aes(x = layer2, y = ELEV),data = elevationlongOTV)+   geom_violin(position=dodge, trim=TRUE, alpha=0.7, aes(fill=Year)) + geom_boxplot(width=0.2,lwd=0.3, position=dodge,outlier.color=NA, aes(color=Year))+
  facet_wrap(~Species,nrow = 4, ncol = 3) + 
  mytheme +
  ylab("Elevation (m)") +
  xlab("")+
  ylim(1000,2500)+
  theme(strip.text = element_text(size=9.5))+
  theme(panel.grid.minor = element_line(colour = "grey", size = 0.5))+ 
  theme(panel.grid.major.y  = element_line(colour = "grey", size = 0.5))+
  scale_y_continuous(limits=c(1200, 2500), breaks=seq(1200,2500,300))+
  scale_fill_manual(values=c("gray30", "green4"))+
  scale_color_manual(values=c("black", "black"))+
  theme(legend.position="right")+
  theme(legend.title = element_blank())
  



```



```{r plot HLI violin by layer}

mytheme<- theme_bw()+ theme(axis.line.x= element_line(colour = "black", size=0.3))+theme(axis.line.y= element_line(colour = "black", size=0.3))+theme(axis.text.x=element_text(size=8, colour = "black"))+theme(axis.text.y=element_text(size=8, colour = "black"))+theme(axis.title=element_text(size=12))+theme(plot.title=element_text(size=6) +theme(plot.title = element_text(hjust = 0.5)))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ theme(legend.position = "none")+ theme(strip.background = element_blank()) + theme(strip.text = element_text(face = "italic"))


HLIbylayer<-ggplot(aes(x = layer2, y = HLI),data = elevationlongOTV)+   geom_violin(position=dodge, trim=TRUE, alpha=0.7, aes(fill=Year)) + geom_boxplot(width=0.2,lwd=0.3, position=dodge,outlier.color=NA, aes(color=Year))+
  facet_wrap(~Species,nrow = 4, ncol = 3) + 
  mytheme +
  ylab("Heat load index") +
  xlab("")+
  theme(strip.text = element_text(size=9.5))+
  theme(panel.grid.minor = element_line(colour = "grey", size = 0.5))+ 
  theme(panel.grid.major.y  = element_line(colour = "grey", size = 0.5))+
  scale_y_continuous(limits=c(1200, 2500), breaks=seq(1200,2500,300))+
  scale_fill_manual(values=c("gray30", "green4"))+
  scale_color_manual(values=c("black", "black"))+
  theme(legend.position="right")+
  theme(legend.title = element_blank())
  



```



```{r plot canopy cover by layer}


head(tree_long3)

##Average by year, layer, spp##


avgcoverbylayer<-tree_long3 %>% group_by(Year, Species, layer2) %>% dplyr::summarise(meancover=mean(Cover, na.rm=FALSE), sdcover=sd(Cover),n=n(), secover=sdcover/sqrt(n))

avgcoverbylayerdf<-as.data.frame(avgcoverbylayer)

avgcoverbylayerdf$Year<-as.factor(avgcoverbylayerdf$Year)



####
mytheme<- theme_bw()+ theme(axis.line.x= element_line(colour = "black", size=0.3))+theme(axis.line.y= element_line(colour = "black", size=0.3))+theme(axis.text.x=element_text(size=8, colour = "black"))+theme(axis.text.y=element_text(size=8, colour = "black"))+theme(axis.title=element_text(size=12))+theme(plot.title=element_text(size=6) +theme(plot.title = element_text(hjust = 0.5)))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ theme(legend.position = "none")+ theme(strip.background = element_blank()) + theme(strip.text = element_text(face = "italic"))



##

coverbylayer<-ggplot(aes(x = layer2, y = meancover,fill = Year,),data = avgcoverbylayerdf) +
  geom_bar(stat="identity",position=position_dodge()) +
  geom_errorbar(aes(ymin=meancover-secover, ymax=meancover+secover), width=.2,position=position_dodge(.9))+
  facet_wrap(~Species,nrow = 3, ncol = 4)+
  ylab("Cover (%)") +
  xlab("")+
  scale_fill_manual(values=alpha(c("gray30", "green4"), 1))+
  theme(strip.text = element_text(size=9.5))+
  theme(panel.grid.minor = element_line(colour = "grey", size = 0.5))+ 
  theme(panel.grid.major.y  = element_line(colour = "grey", size = 0.5))+
  scale_y_continuous(limits=c(0, 30), breaks=seq(0,30,10))+
  theme(legend.position="right")+
  theme(legend.title = element_blank())+
  mytheme


##add stars for significance in paint##



```



```{r plot canopy cover total}

head(avgcovertotal)


avgcovertotaldf<-as.data.frame(avgcovertotal)

mytheme<- theme_bw()+ theme(axis.line.x= element_line(colour = "black", size=0.3))+theme(axis.line.y= element_line(colour = "black", size=0.3))+theme(axis.text.x=element_text(size=8, colour = "black"))+theme(axis.text.y=element_text(size=8, colour = "black"))+theme(axis.title=element_text(size=12))+theme(plot.title=element_text(size=6) +theme(plot.title = element_text(hjust = 0.5)))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ theme(legend.position = "none")+ theme(strip.background = element_blank()) + theme(strip.text = element_text(face = "italic"))


###species names###
avgcovertotaldf2<-avgcovertotaldf%>%mutate(SPECIES2 = SPECIES)
avgcovertotaldf2$SPECIES2<-plyr::mapvalues(avgcovertotaldf2$SPECIES2, from=c("ABCO", "ABLAS", "ABMA", "CADE", "PIBR", "PICO", "PIEN", "PILA", "PIMO", "PIPO", "PSME", "TSME"), to=c("Abies concolor", "Abies lasiocarpa", "Abies magnifica", "Calocedrus decurrens", "Picea breweriana", "Picea engelmannii", "Pinus contorta","Pinus lambertiana","Pinus monticola", "Pinus ponderosa", "Pseudotsuga menziesii", "Tsuga mertensiana"))


covertotal<-ggplot(aes(x = SPECIES2, y = meancover,fill = YEAR,),data = avgcovertotaldf2) +
  geom_bar(stat="identity",position=position_dodge()) +
  geom_errorbar(aes(ymin=meancover-secover, ymax=meancover+secover), width=.2,position=position_dodge(.9))+
  mytheme +
  ylab("Total Cover (%)") +
  xlab("")+
  scale_fill_manual(values=alpha(c("gray30", "green4"), 1))+
  theme(strip.text = element_text(size=9.5))+
  theme(panel.grid.minor = element_line(colour = "grey", size = 0.5))+ 
  theme(panel.grid.major.y  = element_line(colour = "grey", size = 0.5))+
  scale_y_continuous(limits=c(0, 30), breaks=seq(0,30,10))+
  theme(legend.position="right")+
  theme(legend.title = element_blank())+
  theme(legend.key.size = unit(0.5, 'cm'))+
  theme(axis.text.x=element_text(angle=50, face="italic",hjust = 1))


```


```{r ordination with cover data}

### spp matrix total cover##

head(totalcover_2)
##

###
#get sums of plot abundance to elimnate plots with no trees
totalcover_2$sum<-rowSums(totalcover_2[c(4:15)])

##remove plot B61 b/c of no trees##

totalcover_final<-totalcover_2 %>% filter(PLOT != "B61")

siteandvegdata<-merge(totalcover_final, env_imp, by="PLOTYEAR")

sitedata<-siteandvegdata %>% select(PLOTYEAR, Plot, Year, ELEV, HLI, TPI_25)



####ORDINATION##

##
spp.rel <-decostand(totalcover_final[4:15], method = "total")



##run Multiple Response Permutations Procedure (MRPP)
mrpp((spp.rel), sitedata$Year, permutations = 999, distance = "bray", weight.type = 1, strata = NULL, parallel = getOption("mc.cores"))

##run ordination
ord <- metaMDS(spp.rel, k=3, autotransform = FALSE)


#######get environmental vector for elevation and hli
##extract just elevation and hli from env matrix
env_elev_hli<-  sitedata[c(4:5)]

#environmental correaltion with axes 
env_fit <- envfit(ord, env_elev_hli, permu = 999)
env_fit

####create plot of species in ordination space  (APPENDIX 8)
#jpeg("sawyer species ordination.jpg", units="in", width = 5, height = 5, res=350)####plot species with env
#par(mfrow=c(2,1))
cols<-c("gray30", "green4")
plot(ord, type="n", cex.lab=2)
plot(env_fit, p.max=0.01, col= "black")

text(ord, display = "spec", cex=.85, col="black", pch=21)
#dev.off()


###

#####create ordination plot with vectors and hulls (FIGURE 7)
#jpeg("sawyer plot ordination.jpg", units="in", width = 6, height = 6, res=350)


plot(ord, type="n", cex.lab=2,cex.axis=2, xlab="NMDS 1", ylab="NMDS 2")
box(lwd=2)
with(sitedata, points(ord, display="sites", col=cols[Year], pch=21, bg=cols[Year]))

with(sitedata, legend("topleft", legend = levels(Year), bty = "n",
                     cex=1, col = cols, pch = 21, pt.bg = cols))


ordiellipse(ord, sitedata$Year, draw="polygon", col = cols, lwd="1",label=FALSE)
plot(env_fit, p.max=0.05, col= "black", cex=1)

#dev.off()



```


```{r plot ordination}

##pull scores from ordination##

NMDSscores<- vegan::scores(ord, display = "sites")

##merge with plot data##

NMDSandplots<-cbind(siteandvegdata, NMDSscores)

###
env_fit 


env_fitdf <- as.data.frame(vegan::scores(env_fit, display = "vectors"))

env_fitdf2<-as.data.frame(env_fit$vectors$arrows*sqrt(env_fit$vectors$r))




arrow_factor <- ordiArrowMul(env_fit)
env_fitdf2 <- as.data.frame(vegan::scores(env_fit, display = "vectors")) * arrow_factor
env_fitdf3 <- cbind(env_fitdf2, vars = rownames(env_fitdf2), Pvalues = env_fit$vectors$pvals, R_squared = env_fit$vectors$r)




env_fitdf <- cbind(env_fitdf, Var = rownames(env_fitdf))

###hulls for plotting###

hulls <- NMDSandplots %>%  slice(chull(NMDS1, NMDS2))

####

mytheme<- theme_bw()+ theme(axis.line.x= element_line(colour = "black", size=0.3))+theme(axis.line.y= element_line(colour = "black", size=0.3))+theme(axis.text.x=element_text(size=8, colour = "black"))+theme(axis.text.y=element_text(size=8, colour = "black"))+theme(axis.title=element_text(size=12))+theme(plot.title=element_text(size=6) +theme(plot.title = element_text(hjust = 0.5)))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ theme(legend.position = "none")+ theme(strip.background = element_blank()) + theme(strip.text = element_text(face = "italic"))


ordinationplot <- ggplot() +stat_ellipse(geom="polygon",alpha = 0.2, data=NMDSandplots, aes(x = NMDS1, y = NMDS2, fill=Year))+ geom_point(data=NMDSandplots, aes(NMDS1, NMDS2, fill=Year), shape = 21, size=0.75)+mytheme+scale_fill_manual(values=alpha(c("gray30", "green4"), 1))+ geom_segment(data = env_fitdf3 , aes(x = 0, xend = NMDS1 * arrow_factor, y = 0, yend = NMDS2 * arrow_factor),
               arrow = arrow(length = unit(0.25, "cm")), colour = "black")  +annotate(geom="text", x=0.1, y=1.3, label="HLI",  color="black")+annotate(geom="text", x=1.5, y=1.5, label="ELEV",  color="black")+ theme(legend.position = c(0.15, 0.85))+theme(legend.key.size=unit(0.7, 'cm'))+theme(legend.title=element_blank())



```



```{r MANTEL TESTS}

head(siteandvegdata)



########MANTEL TESTS

###1969 DATA
##create species AND env matrix
comp_1969<-siteandvegdata %>% filter(Year==1969) %>% select(ABCO:TSME)
env_1969<-siteandvegdata %>% filter(Year==1969) %>% select(PLOTYEAR, Plot:TPI_25)


veg.dist1969 <- vegdist((comp_1969)) # Bray-Curtis


########2015
##create species wide species matrix

comp_2015<-siteandvegdata %>% filter(Year==2015) %>% select(ABCO:TSME)
env_2015<-siteandvegdata %>% filter(Year==2015) %>% select(PLOTYEAR, Plot:TPI_25)


veg.dist2015 <- vegdist((comp_2015)) # Bray-Curtis



####elevation

elev.dist <- vegdist(env_1969$ELEV, "euclid")
elev_mantel_1969<-mantel((veg.dist1969), elev.dist)
elev_mantel_1969
elev_decay.exp_1969<-decay.model((1 - veg.dist1969 + 0.00001), (elev.dist), model.type="exponential", perm=100)
elev_decay.exp_1969


elev_mantel_2015<-mantel((veg.dist2015), elev.dist)
elev_mantel_2015
elev_decay.exp_2015<-decay.model((1 - veg.dist2015 + 0.00001), elev.dist, model.type="exponential", perm=100)
elev_decay.exp_2015

diffslope(elev.dist, veg.dist1969, elev.dist,  veg.dist2015, permutations = 999, ic=TRUE)


hli.dist <- vegdist(env_1969$HLI, "euclid")
hli_mantel_1969<-mantel(veg.dist1969, hli.dist)
hli_mantel_1969
hli_decay.exp_1969<-decay.model((1 - veg.dist1969 + 0.00001), (hli.dist), model.type="exponential", perm=100)
hli_decay.exp_1969

hli_mantel_2015<-mantel(veg.dist2015, hli.dist)
hli_mantel_2015
hli_decay.exp_2015<-decay.model((1 - veg.dist2015 + 0.00001), (hli.dist), model.type="exponential", perm=100)
hli_decay.exp_2015

diffslope(hli.dist, veg.dist1969, hli.dist,  veg.dist2015, permutations = 999, ic=TRUE)

###for the values in Table 4##

elev_decay.exp_1969
elev_decay.exp_2015

hli_decay.exp_1969
hli_decay.exp_2015

```




```{r plot decay functions}

###

par(mfrow=c(1,2))
####
plot.decay(elev_decay.exp_2015, col="white", ylim=c(0,.7), main="Elevation")
plot.decay(elev_decay.exp_1969, col="gray30", remove.dots=TRUE, add=TRUE, lwd=2, cex=0.75)
plot.decay(elev_decay.exp_2015, col="green4", remove.dots=TRUE, add=TRUE,  lwd=2, cex=0.75)
legend(800, 0.7, legend=c("1969", "2015"),lty=1:1,
       col=c("gray30","green4"), lwd=2, box.lty=0)

##HLI PLOT
plot.decay(hli_decay.exp_2015, col="white", ylim=c(0,.7), main="Heat Load Index")
plot.decay(hli_decay.exp_1969, col="grey30", remove.dots=TRUE, add=TRUE, lwd=2)
plot.decay(hli_decay.exp_2015, col="green4", remove.dots=TRUE, add=TRUE, lwd=2)
legend(0.5, 0.7, legend=c("1969", "2015"),lty=1:1,
       col=c("gray30","green4"), lwd=2, box.lty=0)

```




```{r plot decay functions using ggplot2}

###

elev_decay.exp_2015df<-as.data.frame(elev_decay.exp_2015$data)


elev_decay.exp_2015df$model

par(mfrow=c(1,2))
####
plot.decay(elev_decay.exp_2015, col="white", ylim=c(0,.7), main="Elevation")
plot.decay(elev_decay.exp_1969, col="gray30", remove.dots=TRUE, add=TRUE, lwd=2, cex=0.75)
plot.decay(elev_decay.exp_2015, col="green4", remove.dots=TRUE, add=TRUE,  lwd=2, cex=0.75)
legend(800, 0.7, legend=c("1969", "2015"),lty=1:1,
       col=c("gray30","green4"), lwd=2, box.lty=0)

##HLI PLOT
plot.decay(hli_decay.exp_2015, col="white", ylim=c(0,.7), main="Heat Load Index")
plot.decay(hli_decay.exp_1969, col="grey30", remove.dots=TRUE, add=TRUE, lwd=2)
plot.decay(hli_decay.exp_2015, col="green4", remove.dots=TRUE, add=TRUE, lwd=2)
legend(0.5, 0.7, legend=c("1969", "2015"),lty=1:1,
       col=c("gray30","green4"), lwd=2, box.lty=0)

```



```{r plot ABCO variability bands}

mytheme<- theme_bw()+ theme(axis.line.x= element_line(colour = "black", size=0.3))+theme(axis.line.y= element_line(colour = "black", size=0.3))+theme(axis.text.x=element_text(size=8, colour = "black"))+theme(axis.text.y=element_text(size=8, colour = "black"))+theme(axis.title=element_text(size=12))+theme(plot.title=element_text(size=14) +theme(plot.title = element_text(hjust = 0.5)))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ theme(legend.position = "none")+ theme(strip.background = element_blank()) + theme(strip.text = element_text(face = "italic"))

head(ABCOcan)

ABCOcan$Year<-as.factor(as.character(ABCOcan$Year))


ABCOcoverelev<-ggplot(aes(x = as.numeric(Elevation2015m), y = Estim,color= Year, fill = Year),data = ABCOcan) +
  geom_point() +
  geom_ribbon(aes(ymin=LowBand, ymax=HighBand), color=NA, alpha=0.2)+
  mytheme +
  ylab("Canopy Cover (%)") +
  xlab("Elevation (m)")+
  annotate(geom="text", x=2300, y=55, label="Abies concolor", size=4, fontface = "italic")+
  scale_color_manual(values=alpha(c("gray30", "green4"), 1))+
  scale_fill_manual(values=alpha(c("gray30", "green4"), 1))+
  theme(legend.position=c(0.76, 0.75))+
  theme(legend.title = element_blank())+
  theme(legend.key.size = unit(0.7, 'cm'))


jpeg("C:/Users/Mitzi/Desktop/Academic Collaborations/Sugar Creek Aug 2020/ABCOvariability.jpeg",width = 4, height = 3,units = 'in', res = 600)
ABCOcoverelev
dev.off()

```


```{r climate variables}

head(bcm_plot19592014_3)

##count months per plot per year##

countmonths<-bcm_plot19592014_3 %>% count(ID, wyear)

####

precipdata<-bcm_plot19592014_3 %>% group_by(ID, wyear, ELEV, HLI) %>% dplyr::summarise(yearlyppt=sum(ppt, na.rm=FALSE))

tmndata<-bcm_plot19592014_3 %>% group_by(ID, Year) %>% dplyr::summarise(tempmin=min(tmn, na.rm=FALSE))

growingseasondata<-bcm_plot19592014_3 %>% filter(Month=="Jun"|Month=="Jul"|Month=="Aug")%>% group_by(ID, Year) %>% dplyr::summarise(gsmax=max(tmx, na.rm=FALSE))

cwddata<-bcm_plot19592014_3 %>% group_by(ID, Year) %>% dplyr::summarise(yearlycwd=sum(cwd, na.rm=FALSE))

####

allclimate<-cbind(precipdata,tempmin=tmndata$tempmin, gsmax=growingseasondata$gsmax, cwd=cwddata$yearlycwd)

###1960s avg###


climate1960s_1<-allclimate %>% filter(wyear>1959 & wyear < 1970)%>% group_by(ID, ELEV, HLI) %>% dplyr::summarise(precip1960s=mean(yearlyppt, na.rm=FALSE), tempmin1960s=mean(tempmin, na.rm=FALSE), gsmax1960s=mean(gsmax, na.rm=FALSE), cwd1960s=mean(cwd, na.rm=FALSE), n=n())

climate1960s_2<-allclimate %>% filter(wyear>1959 & wyear < 1970)%>% group_by(ID, ELEV, HLI) %>% dplyr::summarise(precip1960s=mean(yearlyppt, na.rm=TRUE), tempmin1960s=mean(tempmin, na.rm=TRUE), gsmax1960s=mean(gsmax, na.rm=TRUE), cwd1960s=mean(cwd, na.rm=TRUE), n=n())

##2000s average##

climate2000s<-allclimate %>% filter(wyear>2004 & wyear < 2015)%>% group_by(ID, ELEV, HLI) %>% dplyr::summarise(precip2000s=mean(yearlyppt, na.rm=TRUE), tempmin2000s=mean(tempmin, na.rm=TRUE), gsmax2000s=mean(gsmax, na.rm=TRUE), cwd2000s=mean(cwd, na.rm=TRUE), n=n())

climate2000s_2<-as.data.frame(climate2000s[,4:7])

climate1960s_2<-as.data.frame(climate1960s)
####

climate1960s2000s_2<-cbind(climate1960s_2, climate2000s_2)


###
climate1960s2000s_2$diffprecip=climate1960s2000s_2$precip2000s-climate1960s2000s_2$precip1960s

climate1960s2000s_2$difftempmin=climate1960s2000s_2$tempmin2000s-climate1960s2000s_2$tempmin1960s

climate1960s2000s_2$diffgsmax=climate1960s2000s_2$gsmax2000s-climate1960s2000s_2$gsmax1960s

climate1960s2000s_2$diffcwd=climate1960s2000s_2$cwd2000s-climate1960s2000s_2$cwd1960s


##relative diff##

climate1960s2000s_2$reldiffprecip=(climate1960s2000s_2$diffprecip/climate1960s2000s_2$precip1960s)*100

climate1960s2000s_2$reldifftempmin=(climate1960s2000s_2$difftempmin/climate1960s2000s_2$tempmin1960s)*100

climate1960s2000s_2$reldiffgsmax=(climate1960s2000s_2$diffgsmax/climate1960s2000s_2$gsmax1960s*100)

climate1960s2000s_2$reldiffcwd=(climate1960s2000s_2$diffcwd/climate1960s2000s_2$cwd1960s)*100

###is regression significant?##

modelprecip<-lm(diffprecip~ELEV+HLI, data=climate1960s2000s_2)
modelGStemp<-lm(diffgsmax~ELEV+HLI, data=climate1960s2000s_2)
modelmintemp<-lm(difftempmin~ELEV+HLI, data=climate1960s2000s_2)
modelCWD<-lm(diffcwd~ELEV+HLI, data=climate1960s2000s_2)

####

mytheme<- theme_bw()+ theme(axis.line.x= element_line(colour = "black", size=0.3))+theme(axis.line.y= element_line(colour = "black", size=0.3))+theme(axis.text.x=element_text(size=10, colour = "black"))+theme(axis.text.y=element_text(size=10, colour = "black"))+theme(axis.title=element_text(size=12))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())



diffprecipplot<-ggplot(aes(x = ELEV, y = diffprecip, color=HLI),data = climate1960s2000s_2) +
  geom_point() +
  mytheme +
  geom_smooth(method='lm', formula= y~x, color="black")+
  ylim(-150, 150)+
  xlim(1200, 2600)+
  ylab(expression(atop("Change in precipitation (mm)", paste("2000s - 1960s"))))+
  xlab("Elevation (m)")+
  scale_colour_viridis()




diffwinterminplot<-ggplot(aes(x = ELEV, y = difftempmin, color=HLI),data = climate1960s2000s_2) +
  geom_point() +
  mytheme +
  geom_smooth(method='lm', formula= y~x, color="black")+
  xlim(1200, 2600)+
  ylim(1.0, 2.6)+
  ylab(expression(atop("Change in min temp(C)", paste("2000s - 1960s"))))+
  xlab("Elevation (m)")+
  scale_colour_viridis()


diffgsmaxplot<-ggplot(aes(x = ELEV, y = diffgsmax, color=HLI),data = climate1960s2000s_2) +
  geom_point() +
  geom_smooth(method='lm', formula= y~x, color="black")+
  mytheme +
  xlim(1200, 2600)+
  ylim(-0.5, 1.7)+
  ylab(expression(atop("Change in max GS temp (C)", paste("2000s - 1960s"))))+
  xlab("Elevation (m)")+
  scale_colour_viridis()

diffCWDplot<-ggplot(aes(x = ELEV, y = diffcwd, color=HLI),data = climate1960s2000s_2) +
  geom_point() +
  xlim(1200, 2600)+
  ylim(-100, 10)+
  geom_smooth(method='lm', formula= y~x, color="black")+
  mytheme +
  ylab(expression(atop("Change in CWD (mm H2O)", paste("2000s - 1960s"))))+
  xlab("Elevation (m)")+
  scale_colour_viridis()

##combine plots###

multiplot(diffprecipplot, diffwinterminplot, diffgsmaxplot,  diffCWDplot, cols=2)

jpeg("C:/Users/Mitzi/Desktop/Academic Collaborations/Sugar Creek Aug 2020/climatediffraw.jpeg",width = 8, height = 6,units = 'in', res = 600)
multiplot(diffprecipplot, diffwinterminplot, diffgsmaxplot,  diffCWDplot, cols=2)
dev.off()


####


```

