---
title: "Cover_elevation_stats_fig"
author: "Melissa DeSiervo" mhdesiervo@gmail.com, desiervm@union.edu
date: "2/25/2024"
output: html_document
---

library(vegan)
library(indicspecies)
library(tidyverse)
library(data.table)
library(ggplot2)
library(gplots)
library(rcompanion)
library(betapart)
library(weights)
library(stringr)
library(viridis)
library(SciViews)
library(here)



```{r import site and tree data, include=FALSE}

###import files tree data and site data##


###reed in long ###
forb_long <- read.csv(here("SAWYER/rawdata/Common_Plants_1969_2024_v2.csv"), header=T)  ## updated in Jan 2025##


##create new columns with PLOT YEAR ###

forb_long2<-forb_long %>% mutate(PLOTYEAR= paste0(Plot, Year))

###create new column with OTV transformation###

forb_long3<-forb_long2 %>% mutate(OTV = 1.415*log(Med_Cover) + 2)

###another column with transformed back to % from OTV##

forb_long4<-forb_long3 %>% mutate(logcover = (OTV-2)/1.415) %>% mutate(coverOTV=exp(logcover))


####Site X Species matrix with Cover###

forb_long4<-forb_long3 %>% select(PLOTYEAR, Taxon, Med_Cover)

forb.wideCover <- reshape(forb_long4, idvar = "PLOTYEAR", timevar = "Taxon", direction = "wide")  
## some doubles in here..but OK for now###

names(forb.wideCover) <- gsub("Med_Cover.", "", names(forb.wideCover))

# Fill in NA's with zeros in wide data set
forb.wideCover[is.na(forb.wideCover)] <- 0


####Site X Species matrix with OTV###

forb_long5<-forb_long3 %>% select(PLOTYEAR, Taxon, OTV)

forb.wideOTV <- reshape(forb_long5, idvar = "PLOTYEAR", timevar = "Taxon", direction = "wide")
## some doubles in here..but OK for now###

names(forb.wideOTV) <- gsub("Med_Cover.", "", names(forb.wideCover))

forb.wideOTV[is.na(forb.wideOTV)] <- 0


##read in table with env data
env_imp <- read.csv(here("SAWYER/rawdata/sitedata_updated.csv"), header=T)


#make year a factor
env_imp$Year<-as.factor(env_imp$Year)


###merge env and sp data cover
all_datCover<-merge(forb.wideCover, env_imp, by="PLOTYEAR")

all_datOTV<-merge(forb.wideOTV, env_imp, by="PLOTYEAR")



```





```{r plot density by year}

##elevation shrubs ###

shrubselev<-subset(elevationlongOTV, Layer=="shrub")

countsp<-shrubselev %>% group_by(Taxon) %>% count(n())

shrubselev2<-shrubselev %>% filter(Taxon!="Chimaphila umbellata") %>% filter(Taxon!="Eriogonum umbellatum")

####
mytheme<- theme_bw()+ theme(axis.line.x= element_line(colour = "black", size=0.3))+theme(axis.line.y= element_line(colour = "black", size=0.3))+theme(axis.text.x=element_text(size=8, colour = "black"))+theme(axis.text.y=element_text(size=8, colour = "black"))+theme(axis.title=element_text(size=12))+theme(plot.title=element_text(size=6) +theme(plot.title = element_text(hjust = 0.5)))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ theme(legend.position = "none")+ theme(strip.background = element_blank()) + theme(strip.text = element_text(face = "italic"))


## medians by year##

medianelevshrubs<-shrubselev%>% group_by(Year) %>% dplyr::summarise(medianelev=median(Elevation, na.rm=TRUE))

medianelevshrubs$Year<-as.factor(medianelevshrubs$Year)

Elevshrubsall<-ggplot(aes(x = Elevation, fill=Year),data = shrubselev2)+
    geom_density(data=subset(shrubselev,Year == '1969'),color = "#F8766D", fill = "#F8766D", alpha = 0.5) +
    geom_density(data=subset(shrubselev,Year == '2024'),color="#619CFF",  fill = "#619CFF", alpha = 0.5)+
  geom_vline(data = medianelevshrubs, aes(xintercept = medianelev, color = Year))+
  mytheme +theme(legend.position = "right")+
  xlab("Elevation (m)") +
  ylab("Frequency")+
  theme(strip.text = element_text(size=9.5))+
  theme(legend.title = element_blank())+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))


shrubselev2$Taxon<-as.factor(shrubselev2$Taxon)

shrubselev2$Taxon = droplevels(shrubselev2$Taxon)


Elevshrubsbyspecies<-ggplot(aes(x = Elevation, fill=Year),data = shrubselev2)+
    geom_density(data=subset(shrubselev2,Year == '1969'),color = "#F8766D", fill = "#F8766D", alpha = 0.5) +
    geom_density(data=subset(shrubselev2,Year == '2024'),color="#619CFF",  fill = "#619CFF", alpha = 0.5)+
  mytheme +theme(legend.position = "right")+
  facet_wrap(~Taxon, nrow = 4)+
  xlab("Elevation (m)") +
  ylab("Frequency")+
  theme(strip.text = element_text(size=9.5))+
  theme(legend.title = element_blank())+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))


##elevation forbs ###

forbselev<-subset(elevationlongOTV, Layer=="herb")


forbselev2<-forbselev %>% filter(Taxon!="Chrysolepis sempervirens") %>% filter(Taxon!="Lonicera conjugialis")%>% filter(Taxon!="Rosa gymnocarpa")%>% filter(Taxon!="Rubus parviflorus") %>% filter(Taxon!="Berberis nervosa") %>% filter(Taxon!="Symphoricarpos mollis")

forbselev2$Taxon<-as.factor(forbselev2$Taxon)

forbselev2$Taxon = droplevels(forbselev2$Taxon)

####
mytheme<- theme_bw()+ theme(axis.line.x= element_line(colour = "black", size=0.3))+theme(axis.line.y= element_line(colour = "black", size=0.3))+theme(axis.text.x=element_text(size=8, colour = "black"))+theme(axis.text.y=element_text(size=8, colour = "black"))+theme(axis.title=element_text(size=12))+theme(plot.title=element_text(size=6) +theme(plot.title = element_text(hjust = 0.5)))+ theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+ theme(legend.position = "none")+ theme(strip.background = element_blank()) + theme(strip.text = element_text(face = "italic"))


## medians by year##

medianelevforbs<-forbselev%>% group_by(Year) %>% dplyr::summarise(medianelev=median(Elevation, na.rm=TRUE))

medianelevforbs$Year<-as.factor(medianelevforbs$Year)

Elevforbsall<-ggplot(aes(x = Elevation, fill=Year),data = forbselev2)+
    geom_density(data=subset(forbselev2,Year == '1969'),color = "#F8766D", fill = "#F8766D", alpha = 0.5) +
    geom_density(data=subset(forbselev2,Year == '2024'),color="#619CFF",  fill = "#619CFF", alpha = 0.5)+
  geom_vline(data = medianelevshrubs, aes(xintercept = medianelev, color = Year))+
  mytheme +theme(legend.position = "right")+
  xlab("Elevation (m)") +
  ylab("Frequency")+
  theme(strip.text = element_text(size=9.5))+
  theme(legend.title = element_blank())


Elevforbsbyspecies<-ggplot(aes(x = Elevation, fill=Year),data = forbselev2)+
    geom_density(data=subset(forbselev2,Year == '1969'),color = "#F8766D", fill = "#F8766D", alpha = 0.5) +
    geom_density(data=subset(forbselev2,Year == '2024'),color="#619CFF",  fill = "#619CFF", alpha = 0.5)+
  mytheme +theme(legend.position = "right")+
  xlab("Elevation (m)") +
  facet_wrap(~Taxon)+
  ylab("Frequency")+
  theme(strip.text = element_text(size=9.5))+
  theme(legend.title = element_blank())+ theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))



```











```{r trial of NPMR}


data(varespec, varechem)
spe <- varespec ; id  <- varechem
i   <- sample(1:nrow(spe), size=floor(0.75*nrow(spe))) # sample
spe <- spe[i, ]          # in-sample species
idi <- id[i, ]           # in-sample predictors
ido <- id[-i, ]          # out-of-sample predictors
nm  <- c('Al', 'K')      # select 1 or 2 gradients of interest

res_npmr <- npmr(spe, idi, ido, nm, nmulti=5)
summary(res_npmr)

Q <- npmr_sens(obj=res_npmr, pick = 'Vaccmyrt', nm)

```








